name: Basic CI/CD

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building..."

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: echo "Testing..."
